apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: "etcd-backup"
    openshift.io/display-name: "etcd-backup"
  labels:
    kubernetes.io/metadata.name: ocp-etcd-backup
  name: ocp-etcd-backup
